---
- name: Setup Vprofile Stack
  hosts: localhost
  connection: local
  gather_facts: False
  tasks: 
    - name: Import VPC setup variables
      include_vars: vars/vpc_setup
    
    - name: Import VPC ID variables
      include_vars: vars/output_vars
    
    - name: Import VPC ID variables
      include_vars: vars/vprofileprostack

    - name: create a new EC2 key pair, returns generated private key # does not display the private key
      ec2_key:
        name: vprokey
        region: "{{region}}"
      register: vprokey_out # stores the private key

    - name: store private key
      copy: 
        content: "{{vprokey_out.key.private_key}}"
        dest: "./loginkey_vpro.pem"
        mode: 0400
      when: vprokey_out.changed # only saves the key when if the key exist before the exectuion of this play

