---
- name: Setup Vprofile Stack
  hosts: localhost
  connection: local
  gather_facts: False
  tasks: 
    - name: Import VPC setup variables
      include_vars: vars/vpc_setup
    
    - name: Import VPC ID variables
      include_vars: vars/output_vars
    
    - name: Import VPC ID variables
      include_vars: vars/vprofileprostack

    - name: create a new EC2 key pair, returns generated private key # does not display the private key
      ec2_key:
        name: vprokey
        region: "{{region}}"
      register: vprokey_out # stores the private key

    - name: store private key
      copy: 
        content: "{{vprokey_out.key.private_key}}"
        dest: "./loginkey_vpro.pem"
        mode: 0400
      when: vprokey_out.changed # only saves the key when if the key exist before the exectuion of this play


    - name: Create load balancer security group
      ec2_security_group:
        name: vproELB-sg
        description: Allow port 80 from everywhere and all ports within the sg
        vpc_id: "{{vpcid}}"
        region: "{{region}}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: vproELBSG_out

    - name: Create vprofile stack security group
      ec2_security_group:
        name: vproStack-sg
        description: Allow port 22 from everywhere and all ports within the sg
        vpc_id: "{{vpcid}}"
        region: "{{region}}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{vproELBSG_out.group_id}}"
          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{BastionHostSGid}}"
      register: vproStackSG_out

    - name: update vprofile stack security group
      ec2_security_group:
        name: vproStack-sg
        description: Allow port 22 from everywhere and all ports within the sg
        vpc_id: "{{vpcid}}"
        region: "{{region}}"
        purge_rules: no
        rules:
          - proto: all
            group_id: "{{vproStackSG_out.group_id}}"
      register: vproStackSG_out
